#!/bin/bash
# TrigMem Session Analysis Script
# Analyzes Claude Code history.jsonl for TrigMem skill usage

HISTORY="${HISTORY_PATH:-$HOME/.claude/history.jsonl}"
OUTPUT_DIR="${OUTPUT_DIR:-./trigmem-analysis}"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
OUTPUT="$OUTPUT_DIR/trigmem-analysis-$TIMESTAMP.md"

mkdir -p "$OUTPUT_DIR"

# Start report
cat > "$OUTPUT" << EOF
# TrigMem Session Analysis

**Generated:** $(date)
**History file:** $HISTORY

---

## Summary

EOF

# Check if history exists
if [[ ! -f "$HISTORY" ]]; then
    echo "⚠️  History file not found: $HISTORY" >> "$OUTPUT"
    echo "Run: export HISTORY_PATH=/path/to/history.jsonl" >> "$OUTPUT"
    cat "$OUTPUT"
    exit 1
fi

# Count total lines (handle wc output format)
TOTAL_LINES=$(wc -l < "$HISTORY" 2>/dev/null | tr -d ' ')
if [[ -z "$TOTAL_LINES" ]]; then TOTAL_LINES=0; fi
echo "**Total lines analyzed:** $TOTAL_LINES" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Skill invocations
echo "## Skill Invocations" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Skill | Invocations | %" >> "$OUTPUT"
echo "|-------|-------------|-----|" >> "$OUTPUT"

total_trigmem=0
for skill in core categories decision storage examples verification; do
    count=$(grep -o "trigmem-$skill" "$HISTORY" 2>/dev/null | wc -l | tr -d ' ')
    if [[ -z "$count" ]]; then count=0; fi
    total_trigmem=$((total_trigmem + count))
    if [[ "$TOTAL_LINES" -gt 0 ]]; then
        pct=$((count * 100 / TOTAL_LINES))
    else
        pct=0
    fi
    echo "| \`trigmem-$skill\` | $count | $pct% |" >> "$OUTPUT"
done

# Pattern invocations
echo "" >> "$OUTPUT"
echo "## Pattern Skill Invocations" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Pattern | Invocations | %" >> "$OUTPUT"
echo "|---------|-------------|-----|" >> "$OUTPUT"

patterns=("nextjs" "rust" "nestjs" "wasm" "vite" "typescript" "tanstack" "tailwind" "tech-decisions" "ux-design" "documentation")
for pattern in "${patterns[@]}"; do
    count=$(grep -o "patterns/$pattern" "$HISTORY" 2>/dev/null | wc -l | tr -d ' ')
    if [[ -z "$count" ]]; then count=0; fi
    if [[ "$TOTAL_LINES" -gt 0 ]]; then
        pct=$((count * 100 / TOTAL_LINES))
    else
        pct=0
    fi
    echo "| \`$pattern\` | $count | $pct% |" >> "$OUTPUT"
done

# Storage decisions
echo "" >> "$OUTPUT"
echo "## Storage Decisions" >> "$OUTPUT"
echo "" >> "$OUTPUT"
claude_md=$(grep -c "CLAUDE.md" "$HISTORY" 2>/dev/null | tr -d ' ')
rules_updates=$(grep -c "rules/" "$HISTORY" 2>/dev/null | tr -d ' ')
skills_created=$(grep -c "skills/" "$HISTORY" 2>/dev/null | tr -d ' ')

echo "- **CLAUDE.md updates:** ${claude_md:-0}" >> "$OUTPUT"
echo "- **Rules updates:** ${rules_updates:-0}" >> "$OUTPUT"
echo "- **Skills created:** ${skills_created:-0}" >> "$OUTPUT"

# Calculate compliance
echo "" >> "$OUTPUT"
echo "## Compliance Score" >> "$OUTPUT"
echo "" >> "$OUTPUT"

opportunities=$((TOTAL_LINES / 100 + 1))
if [[ "$opportunities" -gt 0 ]]; then
    score=$((total_trigmem * 100 / (opportunities * 5 + 1)))
else
    score=0
fi

echo "**Score:** $score%" >> "$OUTPUT"
echo "" >> "$OUTPUT"

if [[ $score -ge 90 ]]; then
    echo "🟢 **Excellent** - TrigMem fully integrated" >> "$OUTPUT"
elif [[ $score -ge 70 ]]; then
    echo "🟡 **Good** - Mostly compliant" >> "$OUTPUT"
elif [[ $score -ge 50 ]]; then
    echo "🟠 **Fair** - Room for improvement" >> "$OUTPUT"
else
    echo "🔴 **Poor** - Needs training" >> "$OUTPUT"
fi

# Recommendations
echo "" >> "$OUTPUT"
echo "## Recommendations" >> "$OUTPUT"
echo "" >> "$OUTPUT"

if [[ $score -lt 90 ]]; then
    echo "- Increase TrigMem skill usage" >> "$OUTPUT"
fi

core_count=$(grep -o "trigmem-core" "$HISTORY" 2>/dev/null | wc -l | tr -d ' ')
decision_count=$(grep -o "trigmem-decision" "$HISTORY" 2>/dev/null | wc -l | tr -d ' ')
examples_count=$(grep -o "trigmem-examples" "$HISTORY" 2>/dev/null | wc -l | tr -d ' ')

if [[ "${core_count:-0}" -eq 0 ]]; then
    echo "- Reference \`trigmem-core\` for methodology questions" >> "$OUTPUT"
fi
if [[ "${decision_count:-0}" -eq 0 ]]; then
    echo "- Use \`trigmem-decision\` for complex choices" >> "$OUTPUT"
fi
if [[ "${examples_count:-0}" -eq 0 ]]; then
    echo "- Reference \`trigmem-examples\` for worked examples" >> "$OUTPUT"
fi

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "*Generated by claude-config/scripts/analyze-trigmem.sh*" >> "$OUTPUT"

# Output to console
cat "$OUTPUT"

# Also save to latest
cp "$OUTPUT" "$OUTPUT_DIR/trigmem-analysis-latest.md"

echo ""
echo "✅ Analysis complete: $OUTPUT"
